= Mukesh Gadupudi - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: TeachConnect

TC is created to help teachers and other educational professionals better manage their contacts and remember their past students. It is tailored for teachers/educational professionals who would prefer to use a Desktop App for managing contacts especially for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, TC will manage your contacts in the wink of an eye!

*Code contributed*: [https://github.com/CS2103JAN2018-W14-B1/main/blob/master/collated/functional/shanmu9898.md[Functional code]] [https://github.com/CS2103JAN2018-W14-B1/main/blob/master/collated/test/shanmu9898.md[Test code]]

=== Enhancement Added: List Display for Shortcut Commands

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=list]

#End of Extract#

---

==== Justification

Teachers or even educational professionals in general have a lot on their hand. When it comes to saving their personalised shortcuts for commands they want, there is a high probability that they forget the shortcut they assigned.

Showing a list of the shortcut words and the commands to which they have assigned this word will be highly useful for them.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=shortcut]

#End of Extract#

---


=== Enhancement Added: Adding Personalised Shortcut for Commands

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=shortcut]

#End of Extract#

---

==== Justification

TeachConnect comes with a lot of features and each feature has its own command word. The most gruelling part is remembering the exact commmand word as stated in the user guide. To overcome this the shortcut command helps keep aliases to the commands there by helping teachers better remember the command words they are comfortable with.

This also eliminates the need for a common shortcut word which many teachers might not be comfortable with. Hence this command is a twist of personalisation packed with the essence of comfort.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=shortcut]

#End of Extract#

---


=== Enhancement Added: Deleting Shortcut Commands

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=deleteshortcut]

#End of Extract#

---

==== Justification

Mistakes are bound to happen and as long as teachers are humans there is a chance that they might make a mistake. In cases when a teacher assigns a wrong shortcut word to a wrong command word or wants to erase the shortcut entirely, this delete shortcut command comes in handy.

There is a also a big chance that the assigned number of alias or shortcuts to a certain key word has become huge and the user wants to clear up a few of them. In cases like this too the delete shortcut command is of utmost use.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=deleteshortcut]

#End of Extract#

---


=== Enhancement Added: Importing Contacts

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=import]

#End of Extract#

---

==== Justification

Teachers are highly socializable people and there is a high probability that they will want to import contacts from other teachers regarding students' contact details. In contexts like these importing contacts is of utmost importance.

There might also be cases where teachers might take over a class from another teacher and hence it should be made easy to transfer all the student details from one teacher's TeachConnect to the other teacher's TeachConnect.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=import]

#End of Extract#

---



=== Enhancement Added: Export Command

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=export]

#End of Extract#

---

==== Justification

For teachers to share contacts when a new teacher takes up a class or just when a new teacher asks for contact details it is necessary to have the export comand.

Since exporting all of the contacts might be redundant and also neglects some confidential contacts, the export command has the feature of exporting a single person or a range of contacts based on tags or just indexes.

Another very important feature is to export to a CSV file (which can be opened in excel) for them to later create or print Contact Books like the older days address book.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=export]

#End of Extract#

---

=== Other contributions

* Created and set up the team repo including the Travis checks,Coveralls,Auto Publishing and Badges.
* Managed all Issues and Milestone by managing the project and assigning work.
* Wrote additional tests to increase coverage.
* Took the role of Team Leader to make important decisions regarding development of product.
* Managed GitHub effectively to keep track of issues, merging Pull requests by resolving conflicts and keeping track of deadlines so that the weekly releases are made on time with a working product.
* Fixed various(5+) bugs in the product including some bugs which existed previously in the product. link:https://github.com/CS2103JAN2018-W14-B1/main/pull/144[`Pull Request Bug Fix Example`]
* Added several Use Cases for features in Developed Guide.
* Improved User Interface design by changing the orientation and location of various parts of UI.
* Helped teammate create his first PR along with helping him setup git and checkstyle. link:https://github.com/CS2103JAN2018-W14-B1/main/pull/82[`Pull Request AutoSort`].
* Contributed in User Guide and Developer Guide to enhance its language link:https://github.com/CS2103JAN2018-W14-B1/main/pull/54[`Pull Request Developer Guide Update`].
* Helped people on the forum with their technical difficulties.
* Managed all final submissions for CS2103T and CS2101.
* Helped in Collating of codes of everyone link:https://github.com/CS2103JAN2018-W14-B1/main/pull/124[`Pull Request Collate`].
