= Rachel Ngo Phuong Thao - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets
:collatedDir: ../../collated

== Project: TeachConnect
TeachConnect is a contact and event management application designed for teachers and educational professionals. +

TeachConnect is designed to best aid users who prefer to enter input using keyboard instead of the Graphical User Interface.

*Code contributed*: +
link:{collatedDir}/main/Sisyphus25.md[Functional code] +
link:{collatedDir}/test/Sisyphus25.md[Test code] +

== Portfolio Purpose
This portfolio was made to document all contribution I have made to the project. +
The contents included are:

. The external behavior of my contributions.
. The justification for their implementation.
. Details of the implementation.


<<<

=== Enhancement Added: Task and Appointment management

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=appointment]

include::../UserGuide.adoc[tag=task]

#End of Extract#

---

==== Justification

---
This feature can help teachers keeping track of any upcoming appointment or task they have. This can be useful for teachers or teaching associates who frequently need to meet up with students and parents for counselling or administrative purposes.

---

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=eventmanagement]

#End of Extract#

---

<<<


=== Enhancement Added: Theme Command

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=theme]

#End of Extract#

---

==== Justification

---
This feature allows the user to customize the GUI of TeachConnect to their own liking and set the GUI colour to one that is most pleasant to their eyes.

---

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=theme]

#End of Extract#

---

<<<

=== Enhancement Proposed (for Version 2.0)
* More classifications for existing contacts: i.e: `student`, `staff`, `friend` instead of just `student`.
* A `get guardian` command which allows the user to quickly retrieve contact detail of the guardian of a student in the contact list.

=== Other contributions

** Added tag colour to `PersonCard` 's tags.
** Added toggle Calendar View command.
** Modified `list` command to allow toggling of list displayed on GUI.
** Improved User Interface design by rearranging position of components in the app, modifying the appearance of cards displayed in the item list and adding app logo and app name.
** Added 2 new themes for the GUI: `light` and `galaxy`.
** Managed issues assignments and issues tracking.
** Managed Github Milestones and ensured all issue for each Milestone could be completed before the deadline.
** Reviewed team members' Pull Requests.
** Fixed bugs for various issues raised by other teammates and testers.
** Contributed to the User Guide and Developer Guide: +
*** Added command usage for several commands. +
*** Added demo images. +
*** Added annotation for tables and figures. +
*** Formatted the contents.
